"""switch data type to time

Revision ID: ad00ab25b81a
Revises: 62b415735e79
Create Date: 2024-02-16 17:27:12.478119

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad00ab25b81a"
down_revision = "62b415735e79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intervals",
        sa.Column("start_at", postgresql.TIME(timezone=True), nullable=False),
    )
    op.add_column(
        "intervals", sa.Column("end_at", postgresql.TIME(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intervals", "end_at")
    op.drop_column("intervals", "start_at")
    # ### end Alembic commands ###
