"""init

Revision ID: 33b0f80c15e4
Revises: 
Create Date: 2024-02-15 08:27:35.384217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b0f80c15e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('tg_bot_id', sa.BIGINT(), nullable=False),
    sa.Column('test_tg_bot', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('earnings',
    sa.Column('earning_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('shift_user_id', sa.BIGINT(), nullable=False),
    sa.Column('confirm', sa.BOOLEAN(), nullable=False),
    sa.Column('dirty', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('earning_id')
    )
    op.create_table('models',
    sa.Column('model_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('time_periods',
    sa.Column('time_period_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('time_period_id')
    )
    op.create_table('agency_model',
    sa.Column('agency_id', sa.BIGINT(), nullable=False),
    sa.Column('model_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agency_id', 'model_id')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('permission_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('emoji', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('work_now', sa.BOOLEAN(), nullable=False),
    sa.Column('wallet', sa.TEXT(), nullable=True),
    sa.Column('time_period_id', sa.BIGINT(), nullable=True),
    sa.Column('role_id', sa.BIGINT(), nullable=True),
    sa.Column('manager_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_period_id'], ['time_periods.time_period_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('fines',
    sa.Column('fine_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('date_fine', sa.DATE(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fine_id')
    )
    op.create_table('pages',
    sa.Column('page_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('model_id', sa.BIGINT(), nullable=False),
    sa.Column('vip', sa.BOOLEAN(), nullable=False),
    sa.Column('sales_commision', sa.NUMERIC(), nullable=False),
    sa.Column('senior_id', sa.BIGINT(), nullable=True),
    sa.Column('number_operator_shift', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('page_link', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('user_tg',
    sa.Column('user_tg_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('tg_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_tg_id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('users_agencies',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('agency_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'agency_id')
    )
    op.create_table('users_models',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('model_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'model_id')
    )
    op.create_table('pages_time_periods',
    sa.Column('page_time_period_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('time_period_id', sa.BIGINT(), nullable=False),
    sa.Column('page_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_period_id'], ['time_periods.time_period_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_time_period_id')
    )
    op.create_table('shifts',
    sa.Column('shift_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('date_shift', sa.DATE(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('page_time_period_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['page_time_period_id'], ['pages_time_periods.page_time_period_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('shifts_users',
    sa.Column('shift_user_id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('operator_id', sa.BIGINT(), nullable=False),
    sa.Column('shift_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts_users')
    op.drop_table('shifts')
    op.drop_table('pages_time_periods')
    op.drop_table('users_models')
    op.drop_table('users_agencies')
    op.drop_table('user_tg')
    op.drop_table('pages')
    op.drop_table('fines')
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_table('agency_model')
    op.drop_table('time_periods')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('models')
    op.drop_table('earnings')
    op.drop_table('agencies')
    # ### end Alembic commands ###
