"""create roles

Revision ID: 487b34e5e665
Revises: edf0d3493308
Create Date: 2024-02-16 08:51:18.612680

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "487b34e5e665"
down_revision = "edf0d3493308"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles")
    # ### end Alembic commands ###
