"""drop agencies_models, add agencies_pages

Revision ID: e10646485942
Revises: 3180c6a6fe00
Create Date: 2024-02-24 12:36:47.420056

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e10646485942"
down_revision = "3180c6a6fe00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies_pages",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("agency_id", sa.BIGINT(), nullable=False),
        sa.Column("page_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", "page_id", name="idx_unique_agency_page"),
    )
    op.drop_table("agencies_models")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies_models",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("agency_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("model_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
            name="agencies_models_agency_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name="agencies_models_model_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="agencies_models_pkey"),
        sa.UniqueConstraint("agency_id", "model_id", name="idx_unique_agency_model"),
    )
    op.drop_table("agencies_pages")
    # ### end Alembic commands ###
